"""Default category taxonomy and deterministic keyword rules for categorization."""
DEFAULT_CATEGORIES = [
    # (name, parent_type, group, is_essential)
    ("Salary", "income", "Income", False),
    ("Interest Income", "income", "Income", False),
    ("Refund", "income", "Income", False),
    ("Other Income", "income", "Income", False),

    ("Housing", "expense", "Housing", True),
    ("Food & Dining", "expense", "Food & Dining", True),
    ("Food Delivery", "expense", "Food & Dining", False),
    ("Groceries", "expense", "Food & Dining", True),
    ("Transportation", "expense", "Transportation", True),
    ("Fuel", "expense", "Transportation", True),
    ("Shopping", "expense", "Shopping", False),
    ("Online Shopping", "expense", "Shopping", False),
    ("Utilities", "expense", "Utilities", True),
    ("Entertainment", "expense", "Entertainment", False),
    ("Subscriptions", "expense", "Subscriptions", False),
    ("Healthcare", "expense", "Healthcare", True),
    ("Education", "expense", "Education", True),
    ("Travel", "expense", "Travel", False),
    ("Insurance", "expense", "Insurance", True),
    ("EMI / Loans", "expense", "EMI / Loans", True),
    ("Bank Charges", "expense", "Bank Charges", True),
    ("Taxes", "expense", "Taxes", True),
    ("Other", "expense", "Other", False),

    ("Transfer", "transfer", "Transfers", False),
    ("Card Payment", "transfer", "Transfers", False),
    ("Cash Withdrawal", "transfer", "Cash Withdrawal", False),
    ("Investments", "investment", "Investments", False),
]

# category_name -> list of keyword patterns matched against normalized description/merchant (uppercase)
KEYWORD_RULES = {
    "Food Delivery": ["SWIGGY", "ZOMATO"],
    "Groceries": ["BIGBASKET", "GROFERS", "BLINKIT", "DMART", "GROCERY"],
    "Food & Dining": ["RESTAURANT", "CAFE", "STARBUCKS", "DOMINOS", "MCDONALD", "PIZZA", "KFC"],
    "Fuel": ["PETROL", "FUEL", "HPCL", "BPCL", "INDIAN OIL", "SHELL"],
    "Transportation": ["UBER", "OLA", "RAPIDO", "IRCTC", "METRO", "PARKING"],
    "Online Shopping": ["AMAZON", "FLIPKART", "MYNTRA", "AJIO", "MEESHO"],
    "Shopping": ["MALL", "RETAIL", "STORE"],
    "Utilities": ["ELECTRICITY", "AIRTEL", "JIO", "VODAFONE", "BSNL", "WATER BILL", "GAS BILL", "BROADBAND"],
    "Entertainment": ["BOOKMYSHOW", "PVR", "INOX", "MOVIE"],
    "Subscriptions": ["NETFLIX", "SPOTIFY", "PRIME VIDEO", "HOTSTAR", "YOUTUBE PREMIUM", "APPLE.COM/BILL", "GOOGLE PLAY"],
    "Healthcare": ["PHARMACY", "HOSPITAL", "CLINIC", "APOLLO", "MEDPLUS", "DIAGNOSTIC"],
    "Education": ["SCHOOL", "COLLEGE", "TUITION", "UDEMY", "COURSERA", "BYJU"],
    "Travel": ["MAKEMYTRIP", "GOIBIBO", "AIRLINES", "INDIGO", "AIRBNB", "OYO", "YATRA"],
    "Insurance": ["INSURANCE", "LIC", "POLICYBAZAAR", "PREMIUM"],
    "EMI / Loans": ["EMI", "LOAN"],
    "Bank Charges": ["ANNUAL FEE", "AMC CHARGE", "SERVICE CHARGE", "PENALTY", "MIN BAL CHARGE"],
    "Taxes": ["INCOME TAX", "GST", "TDS"],
    "Investments": ["MUTUAL FUND", "SIP", "ZERODHA", "GROWW", "UPSTOX", "NPS", "STOCKS", "ETF", "GOLD BOND"],
    "Salary": ["SALARY", "SAL CREDIT", "PAYROLL"],
    "Interest Income": ["INTEREST CREDIT", "INT.PD", "SAVINGS INTEREST"],
    "Cash Withdrawal": ["ATM", "CASH WDL", "CASH WITHDRAWAL"],
    "Transfer": ["UPI", "NEFT", "IMPS", "RTGS", "FUND TRANSFER"],
    "Card Payment": ["CREDIT CARD PAYMENT", "CC PAYMENT", "CARD BILL PAYMENT"],
}
